sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install tox-travis
  - pip install tox
  - pip install coverage coveralls
branches:
  only:
    travis
script:
  - tox -r
after_success:
  - coverage report
  - coveralls
